Find paper an polygon contours algorithm
OvechkinDanil/Intelligent-Placer pull request #5
Opened 2022-03-26 17:42 UTC by OvechkinDanil

2022-04-04 13:22 UTC, sqrtyyy requested changes

2022-04-04 13:22 UTC, sqrtyyy commented on src/intelligent-placer.py
> +    filter = cv2.inRange(img_hsv, np.array([0, 0, 169]), np.array([255, 255, 255]))
Это ключевое слово языка. Лучше его так его не переопределять, иначе потом возникнут проблемы. Далее по коду то же самое нужно исправить.

2022-04-04 13:22 UTC, sqrtyyy commented on src/intelligent-placer.py
> +    prox_measure = 14
Можно хранить только пару из макс площади и её индекса.
```suggestion
    prox_measure = 14
    
    max_area = 0
    max_area_idx = -1
    
    for i, cnt in enumerate(contours):
        contour_area = cv2.contourArea(cnt)
        if contour_area > max_area:
            max_area = contour_area
            max_area_idx = i
            
        if contour_area > min_contour_area:
            good_contours.append(cnt)
            M = cv2.moments(cnt)
            cx.append(int(M['m10'] / (M['m00'] + 1e-5)))
            cy.append(int(M['m01'] / (M['m00'] + 1e-5)))
    
```

2022-04-06 22:01 UTC, pikabol88 commented on README.md
> +3. Ответ на вопрос из постановки задачи [В разработке]
План написан очень абстрактно
Думаю, на следующих этапах разработки лучше описать шаги каждого из пунктов более развернуто

2022-04-10 10:40 UTC, OvechkinDanil commented on src/intelligent-placer.py
> +    prox_measure = 14
Действительно хорошее замечание. Исправил в новой версии

2022-04-10 10:40 UTC, OvechkinDanil commented on src/intelligent-placer.py
> +    filter = cv2.inRange(img_hsv, np.array([0, 0, 169]), np.array([255, 255, 255]))
Исправил

2022-04-10 10:40 UTC, OvechkinDanil commented on README.md
> +3. Ответ на вопрос из постановки задачи [В разработке]
Доработал план работы в новой версии

2022-04-11 16:47 UTC, sqrtyyy requested changes

2022-04-11 16:47 UTC, sqrtyyy commented on intelligent_placer_lib/intelligent_placer.py
> +    sum = 0
sum - тоже встроенное имя, лучше исправить
Также можно сделать так:
sum_areas = sum(cv.contourArea(obj) for obj in object_rectangles).

2022-04-11 16:47 UTC, sqrtyyy commented on intelligent_placer_lib/intelligent_placer.py
> +    objects = list()
Не очень понимаю смысла функции, почему бы не сделать
```suggestion
list(contours[0])
```
или
```suggestion
    objects = [contour for contour in contours[0]]
```

2022-04-11 16:47 UTC, sqrtyyy commented on intelligent_placer_lib/intelligent_placer.py
> +    rect_size = len(rectangle)
Опционально:
можно сократить и ускорить код
```suggestion
    cond = lambda elem: elem[0] < delta or elem[1] < delta or elem[0] >= w - delta or elem[1] >= h - delta
    out_of_bounds_num = sum(cond(elem) for elem in rectangle)
    if out_of_bounds_num == len(rectangle):
        return False
```

2022-04-11 17:02 UTC, sqrtyyy commented on README.md
> +Изображение в формате jpeg предеметов и многоугольника, который нарисован темным маркером на белом листе бумаги. На фотографии лист бумаги и предметы лежат на ярко-зеленой поверхности. Лист бумаги с
Является ли условие "ярко-зеленой поверхности." обязательным?
Если да, то в "Отличается от цвета листа, на котором лежат предметы(не белый)"(46 строка) нужно дописать.
Если нет, то, наверное, стоит убрать

2022-04-16 13:33 UTC, OvechkinDanil commented on intelligent_placer_lib/intelligent_placer.py
> +    sum = 0
Исправил

2022-04-16 13:34 UTC, OvechkinDanil commented on intelligent_placer_lib/intelligent_placer.py
> +    objects = list()
Изначально предполагалось, что в этом методе буду какие-то дополнительные условия по фильтрации объектов, но я их добавил в другое место, и забыл отрефакторить этот метод. Спасибо за замечание!

2022-04-16 13:35 UTC, OvechkinDanil commented on intelligent_placer_lib/intelligent_placer.py
> +    rect_size = len(rectangle)
Изменил

2022-04-19 08:31 UTC, pikabol88 commented on README.md
> +    1.1. Бинаризация изображения с помщью морфологических операций
опечатка

2022-04-19 08:32 UTC, pikabol88 commented on README.md
> +	2.1. С помщью детектора Кэнни и морфологических операций определены
опечатка и, возможно, незаконченное предложение

2022-04-19 08:41 UTC, pikabol88 commented on intelligent_placer_lib/intelligent_placer.py
> +    return max_allowable_area > cv2.contourArea(rectangle) > min_allowable_area
Появляются константы, которые задают ограничения прямоугольнику. Но в описаниях требований к входным данным таких ограничений нет

2022-04-19 08:47 UTC, pikabol88 requested changes
Необходимо исправить опечатки в плане решения задачи и дополнить требования, в соответствии с текущим алгоритмом

2022-04-21 20:24 UTC, OvechkinDanil commented on README.md
> +Изображение в формате jpeg предеметов и многоугольника, который нарисован темным маркером на белом листе бумаги. На фотографии лист бумаги и предметы лежат на ярко-зеленой поверхности. Лист бумаги с
Исправил, но забыл отписаться

2022-04-21 20:25 UTC, OvechkinDanil commented on README.md
> +	2.1. С помщью детектора Кэнни и морфологических операций определены
Будет исправлено в следующем коммите

2022-04-21 20:25 UTC, OvechkinDanil commented on intelligent_placer_lib/intelligent_placer.py
> +    return max_allowable_area > cv2.contourArea(rectangle) > min_allowable_area
Постараюсь доработать требования так, чтобы они соответствовали текущей реализации алгоритма. Спасибо за замечание!

2022-04-23 12:03 UTC, OvechkinDanil commented on README.md
> +    1.1. Бинаризация изображения с помщью морфологических операций
исправил

2022-04-23 12:04 UTC, merged